### PR TITLE
Update and rename bootstrap-riscv64.yml to bootstrap.yaml

### PR DESCRIPTION
**Pull request by tqh**
* Add arm, arm64 and x86_64 as targets to build
* Do full bootstrap
* Use github repos as they are much faster to checkout
* get latest tag with regexp magic

(Sharing code between jobs are slow, so do checkout for each target)

### CODE REVIEW

**Comment by pulkomandy** [comment]
Why not sparc, m68k and PowerPC? At least sparc should get this far into bootstrap without much problems.

Are the resulting bootsrap packages exposed somewhere? (as build artifacts or something?) that would be convenient to then do the next steps of the bootstrap process locally

**Comment by tqh** [comment]
You only have certain amount of free build minutes. If someone wants more targets they can change the target line.

No artifacts, exposing them would need storage space, as there is a size limit on build artefacts. I guess someone can add that later once we have a good place to store them.

**Comment by tqh** [comment]
It would probably be good to setup a github runner on a machine somewhere...

**Comment by tqh** [comment]
Having bootstrap logs from different arches is already very useful, so merging it as is.

**Pull request merged**
