### PR TITLE
gcc: add recipe for version 13.1.0

### PR DESCRIPTION
**Pull request by davidkaroly**

### CODE REVIEW

**Comment by pulkomandy** [comment]
This and your binutils recipe are both marked as untested on all architectures, so they will not be used. Should we merge them as-is, or do you plan to test and enable them?

**Comment by davidkaroly** [comment]
I plan to revisit them. Already had a successful build for arm (even though I'd like to redo that with a clean working dir as there was a lot of churn), arm64 and riscv64 still to be tested.

**Comment by pulkomandy** [comment]
Another comment: it may be a good idea to change the "revision" on all packages so we know what we're working with. Maybe doing them all at once when they are rebuilt with gcc13 is the best way to go.

**Comment by tqh** [comment]
I merged binutils already, but changing the recipe is just another PR anyway.

**Comment by davidkaroly** [comment]
test results so far:
successful build on arm and riscv64
one more patch needed on arm64 for the LSE stuff in libgcc

**Comment by tqh** [comment]
I started a build where I added `--with-arch=armv8.1-a` to the recipe to see if it will use atomics directly. (Just for testing, lets use libatomic if we can..)

**Comment by tqh** [comment]
It didn't work.

**Comment by davidkaroly** [comment]
This additional patch will build the LSE atomic functions in libgcc. It seems to be done this way on all platforms except netbsd:
https://github.com/gcc-mirror/gcc/commit/33befddcb849235353dc263db1c7d07dc15c9faa

The other change is added for the sake of consistency:
https://github.com/gcc-mirror/gcc/commit/012310aafb24e8ccdc0d979e79bf7c867a52e615

**Comment by tqh** [comment]
Looks good to me, do we want to enable it for all? I suggest we merge and maybe do a 13.2?

**Comment by tqh** [comment]
Any changes we do here we should also have in buildtools gcc so they behave similar...

**Comment by davidkaroly** [comment]
> Any changes we do here we should also have in buildtools gcc so they behave similar...

yes that's what I intend to do, but it's not so easy for gcc-13.1 as the buildtools repo already contains 13.2 and probably we don't want to branch out a gcc-13.1 maintenance branch. So for now we can keep this patch here for 13.1 and next I'd like to submit it to buildtools repo for 13.2 (once I had a chance to test it). 

Then we won't need a downstream patch in the recipe for 13.2 as we can reference a commit hash which will contain this patch.

**Comment by tqh** [comment]
Not sure I understand from your comment what is next step for this PR. Should we merge it, or instead merge a 13.2 version?

**Comment by davidkaroly** [comment]
i think we should merge it

**Pull request merged**
